function alignMap(data,resp,pMaps)

fMap = figure('name',sprintf('%s - Cell map in response to %s',data.label,data.fName), ...
              'numberTitle','off');
whitebg(fMap,'k')
axMap = axes('parent',fMap, ...
             'ydir','reverse', ...
             'cLim',[0 max(resp)], ...
             'DataAspectRatio',[1 1 1], ...
             'xtick',[], ...
             'ytick',[]);
hold(axMap,'on')
pcolor(axMap,mapCells(resp,pMaps))
hold(axMap,'off')
axis(axMap,'image')
shading(axMap,'flat')
cbMap = colorbar(axMap,'southOutside');
xlabel(cbMap,'Cell response')