function alignGUI

%% Create figure
GUI.fig = figure('menubar','none', ...
                 'name','Calcium imaging GUI', ...
                 'numbertitle','off', ...
                 'position',[100,100,600,400]);


%% Create loading portion
% Portion to load in calcium imaging data from .txt file

% Positioning
xLoad = ;
yLoad = ;

% Title
uicontrol('parent',GUI.fig, ...
          'style','text', ...
          'position',[xLoad,yLoad,w,h], ...
          'string','Cellular response data', ...
          'backgroundColor',bgColor, ...
          'horizontalAlignment','left');

% Response file options
% Load button
uicontrol('parent',GUI.figFocus, ...
          'style','pushButton', ...
          'position',[xLoad,yLoad,w,h], ...
          'string','Load responses', ...
          'backgroundColor',bgColor, ...
          'horizontalAlignment','center');
% Response file
uicontrol('parent',GUI.fig, ...
          'style','editBox', ...
          'position',[xLoad,yLoad,w,h], ...
          'string','[no file chosen]', ...
          'backgroundColor',bgColor, ...
          'horizontalAlignment','left');

% Time shift options
uicontrol('parent',GUI.fig, ...
          'style','text', ...
          'position',[xLoad,yLoad,w,h], ...
          'string','Shift time:', ...
          'backgroundColor',bgColor, ...
          'horizontalAlignment','right');
uicontrol('parent',GUI.fig, ...
          'style','editBox', ...
          'position',[xLoad,yLoad,w,h], ...
          'string','0', ...
          'backgroundColor',bgColor, ...
          'horizontalAlignment','center');


%% Create session variable portion
% Portion to load and list session variables.

% Positioning
xVar = ;
yVar = ;

% Title
uicontrol('parent',GUI.fig, ...
          'style','text', ...
          'position',[xLoad,yLoad,w,h], ...
          'string','Session variables', ...
          'backgroundColor',bgColor, ...
          'horizontalAlignment','left');

% List box of variables

